model:
  classes: 40
  learnable_w: true
  hidden_dims: [128]
  dropout_rate: 0.5
  with_bias: true
  activation: "relu"
trainer: 
  learning_rate: 0.001
  epochs: 1000
  output_stepsize: 10
  loss_fn: "cross_entropy"
lr_scheduler:
  step_size: 100
  gamma: 0.9
task_type: "classification"
data:
  g_path: ""
  dvh_path: ""
  invde_ht_dvh_path: ""
  labels_path: "../data/m_g_ms_gs/labels.mtx"
  features_path: ""
  test_idx: 9842