model:
  classes: 40
  hidden_dims: [128]
  dropout_rate: 0.5
  with_bias: true
  activation: "relu"
trainer: 
  learning_rate: 0.001
  epochs: 1000
  output_stepsize: 10
  loss_function: "cross_entropy"
lr_scheduler:
  step_size: 100
  gamma: 0.9
task_type: "classification"
data:
  g_path: "../data/m_g_ms_gs/G_coo.csv"
  labels_path: "../data/m_g_ms_gs/lbls_m_g_ms_gs.csv"
  features_path: "../data/m_g_ms_gs/fts_m_g_ms_gs.csv"
  test_idx: 9842