model:
  classes: 40
  distributed: false
  learnable_w: false
  hidden_dims: [256]
  dropout_rate: 0.5
  with_bias: true
  activation: "relu"
trainer: 
  learning_rate: 0.001
  epochs: 500
  output_stepsize: 5
  loss_fn: "cross_entropy"
lr_scheduler:
  step_size: 100
  gamma: 0.9
task_type: "classification"
data:
  dataset: "ModelNet40"
  g_path: "../data/m_g_ms_gs/G_coo.csv"
  dvh_path: "../data/m_g_ms_gs/DVH_coo.csv"
  invde_ht_dvh_path: "../data/m_g_ms_gs/invDE_HT_DVH_coo.csv"
  labels_path: "../data/m_g_ms_gs/labels.csv"
  features_path: "../data/m_g_ms_gs/features.csv"
  test_idx: 9842