model:
  dataset: "ModelNet40"
  classes: 40
  distributed: false
  learnable_w: false
  hidden_dims: [128]
  dropout_rate: 0
  with_bias: true
  activation: "relu"
trainer: 
  learning_rate: 0.001
  epochs: 1000
  output_stepsize: 5
  loss_fn: "cross_entropy"
lr_scheduler:
  step_size: 100
  gamma: 0.9
task_type: "classification"
data:
  g_path: "../data/m_g_ms_gs/G.mtx"
  dvh_path: "../data/m_g_ms_gs/DVH.mtx"
  invde_ht_dvh_path: "../data/m_g_ms_gs/invDE_HT_DVH.mtx"
  labels_path: "../data/m_g_ms_gs/labels.mtx"
  features_path: "../data/m_g_ms_gs/features.mtx"
  test_idx: 9842